In [2]:
import numpy as np
import pandas as pd

# 1. Student Marks Analysis
- Write a Python program using NumPy to create a 1D array of student marks.
- Find and display the mean, maximum, minimum, and standard deviation of the marks.

In [3]:
marks = np.random.randint(10,90,size=(30))
marks

array([10, 48, 69, 13, 68, 79, 56, 25, 14, 33, 43, 65, 75, 59, 23, 12, 64,
       73, 46, 65, 75, 87, 68, 21, 69, 55, 33, 28, 81, 71])

In [4]:
marks.mean()

np.float64(50.93333333333333)

In [5]:
marks.max()

np.int64(87)

In [6]:
marks.min()

np.int64(10)

In [7]:
marks.std()

np.float64(23.493166855255783)

# 2. Matrix Operations
- Create two 3×3 NumPy matrices with integer elements.
- Perform and display the results of addition, subtraction, and matrix
multiplication between the two matrices.

In [8]:
arr1 = np.random.randint(10,size=(3,3))
arr1

array([[3, 3, 8],
       [0, 0, 0],
       [3, 3, 9]])

In [9]:
arr2 = np.random.randint(10,size=(3,3))
arr2

array([[2, 1, 7],
       [7, 8, 2],
       [0, 4, 0]])

In [10]:
arr1 + arr2

array([[ 5,  4, 15],
       [ 7,  8,  2],
       [ 3,  7,  9]])

In [11]:
arr1 - arr2

array([[ 1,  2,  1],
       [-7, -8, -2],
       [ 3, -1,  9]])

In [12]:
# np.matmul(arr1,arr2)
arr1 @ arr2

array([[27, 59, 27],
       [ 0,  0,  0],
       [27, 63, 27]])

# 3. Temperature Conversion
- Create a NumPy array containing temperature values in Celsius.
- Convert all values to Fahrenheit using vectorized operations (Formula: F = (C × 9/5) +
32).
o Display both Celsius and Fahrenheit arrays.

In [13]:
temp = np.random.randint(30,size=(10))
temp

array([21, 20, 27, 15, 29, 13,  8,  6,  9, 29])

In [14]:
temp_res = ((temp*9/5)+32)
temp_res

array([69.8, 68. , 80.6, 59. , 84.2, 55.4, 46.4, 42.8, 48.2, 84.2])

# 4. Sales Report Analysis
- Generate random daily sales data for 10 consecutive days using NumPy’s random
functions.
- Calculate and display:
1. Total sales
2. Average (mean) sales
3. The day number with the highest sales.

In [15]:
sales = np.random.randint(5000,10000,size=(10))
sales

array([6576, 6888, 8240, 8790, 6126, 6125, 5044, 9420, 5880, 9538])

In [16]:
sales.sum()

np.int64(72627)

In [17]:
sales.mean()

np.float64(7262.7)

In [18]:
sales.max()

np.int64(9538)

5. Conditional Extraction
- Create a NumPy array of integers.
- Use boolean masking to extract and print all even elements from the array.
- Verify the output by comparing it with manual filtering logic.

In [19]:
arr3 = np.random.randint(20,size=(20))
arr4 = []
arr3

array([ 8, 10,  4, 11,  8,  0, 19, 11, 12,  9,  7, 10,  0,  2, 16, 18,  6,
        6, 13,  8])

In [20]:
mask = arr3%2==0
mask

array([ True,  True,  True, False,  True,  True, False, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True])

In [21]:
cnt = 0
for i in mask:
  cnt+1
  if i == "np.True_":
    arr4.append(arr3[cnt])

arr4

[]

In [22]:
mask[0]

np.True_

# 6. Create a DataFrame Create a DataFrame with employee details (Name, Age, Department, Salary).
- Add a new column for "Bonus = 10% of Salary".
- Display only employees in "IT" with salary > 50,000.

In [23]:
df1 = pd.DataFrame(columns=["Name","Age","Department","Salary"],)

# 7. CSV Operations Read a CSV file of student marks.
- Display top 5 records.
- Find the average marks of all students.

In [24]:
marks = np.random.randint(30,100,size=(20))
test = pd.DataFrame({"Marks":marks})
test.to_csv('test.csv')

In [25]:
test1 = pd.read_csv('test.csv')

In [26]:
test1.head()

Unnamed: 0  Marks
0           0     86
1           1     83
2           2     40
3           3     61
4           4     80

In [27]:
np.mean(test1['Marks'])

np.float64(67.9)

# 8. Handling Missing Values Create a DataFrame with some missing data.
- Fill missing values with the mean of the column.
- Drop rows that still contain missing values.

In [31]:
df_missing = pd.read_csv('test.csv')
df_missing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  20 non-null     int64
 1   Marks       20 non-null     int64
dtypes: int64(2)
memory usage: 452.0 bytes


In [46]:
df_missing['Marks']

0     86.0
1     83.0
2     40.0
3     61.0
4     80.0
5     82.0
6     88.0
7     86.0
8     92.0
9     51.0
10    76.0
11     NaN
12     NaN
13    95.0
14    56.0
15    87.0
16    38.0
17     NaN
18    45.0
19    36.0
Name: Marks, dtype: float64

In [49]:
df_missing['Marks'][[11, 12,17]] = np.nan
df_missing

/tmp/ipython-input-495321428.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_missing['Marks'][[11, 12,17]] = np.nan
/tmp/ipython-input-495321428.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a Da

Unnamed: 0  Marks
0            0   86.0
1            1   83.0
2            2   40.0
3            3   61.0
4            4   80.0
5            5   82.0
6            6   88.0
7            7   86.0
8            8   92.0
9            9   51.0
10          10   76.0
11          11    NaN
12          12    NaN
13          13   95.0
14          14   56.0
15          15   87.0
16          16   38.0
17          17    NaN
18          18   45.0
19          19   36.0

In [52]:
df_missing = df_missing.dropna()
df_missing.info()


<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 0 to 19
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  17 non-null     int64  
 1   Marks       17 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 408.0 bytes


# 9. Grouping Data Group a DataFrame of sales by region and find total sales in each region.

# 10. Data Merge Merge two DataFrames:
- students (id, name)
- scores (id, marks) Display merged data showing student name and marks.

In [4]:
id = np.arange(1,11)
id
name -
marks = np.random.randint(33,99,size=(10))
marks


array([38, 72, 50, 60, 70, 33, 38, 50, 53, 67])

# 11. Basic Line Plot Create a line plot for monthly sales data. Label axes and title the plot “Monthly Sales Trend”.

# 12. Bar and Pie Plot Plot a bar chart showing the number of students per department (e.g., CS, IT, ECE). Also, represent the same data using a pie chart.

# 13. Scatter Plot Analysis Plot a scatter plot showing “Hours Studied” vs “Exam Score” and analyze the relationship.

# 14. Histogram Plot Create a histogram for the ages of 50 employees to visualize the age distribution.

# 15. Subplots Practice Display four different plots (line, bar, histogram, scatter) using subplots (2x2 grid).