In [15]:
import numpy as np
import pandas as pd


In [16]:
df = pd.read_csv('data.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
x= df.iloc[:,1:2].values
y= df.iloc[:,2:3].values

In [ ]:
x

In [ ]:
y

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(x_train,y_train,color = 'red')
plt.plot(x_train,regressor.predict(x_train),color = 'blue')
plt.show()

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=4)
x_poly = poly_reg.fit_transform(x)
lin_reg2 = LinearRegression()
lin_reg2.fit(x_poly,y)

In [ ]:
plt.scatter(x,y, color='red')
plt.plot(x, lin_reg2.predict(x_poly))

In [ ]:
lin_reg2.predict(poly_reg.fit_transform([[6.5]]))

In [ ]:
regressor.predict([[6.5]])

In [ ]:
df1 = pd.read_csv('D8data1.csv')
df1

In [ ]:
from matplotlib import pyplot as plt
sns.scatterplot(x=df1['Age'], y=df1['EstimatedSalary'], hue=df1['Purchased'])
plt.gca().spines[['top', 'right',]].set_visible(False)

In [ ]:
sns.histplot(df1, x='Age', hue='Purchased', kde=True)
plt.title('Age Distribution by Purchased Status')
plt.xlabel('Age')
plt.ylabel('Count')
plt.show()

In [ ]:
df1.info()

In [ ]:
df1.describe()

# EDA

In [ ]:
import seaborn as sns


In [ ]:
sns.countplot(x=df1['Purchased'], hue=df1['Gender'])

In [ ]:
sns.distplot(df1['Age'])

# Task
Visualize the distribution of 'Age' in the `df1` DataFrame, with 'Purchased' as the hue and 'Gender' as columns, using `sns.displot`. Then, provide insights from these plots regarding the relationship between age, gender, and purchasing behavior.

## Visualize Age Distribution by Purchased Status and Gender

### Subtask:
Create a `sns.displot` to show the distribution of 'Age', with 'Purchased' as the hue, and 'Gender' as columns to separate the plots by gender. This will allow for a comprehensive view of how age and gender relate to purchasing behavior.


**Reasoning**:
I need to create a distribution plot using `sns.displot` as specified in the instructions. The plot will show the distribution of 'Age', with 'Purchased' as the hue, and 'Gender' as columns to separate the plots. This will help visualize the relationship between age, gender, and purchasing behavior.



In [ ]:
sns.displot(df1, x='Age', hue='Purchased', col='Gender', kde=True)
plt.suptitle('Age Distribution by Purchased Status and Gender', y=1.02)
plt.show()

In [ ]:
x = df1[['Age','EstimatedSalary']]
y = df1['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=3)

In [ ]:
x_train, x_test

In [ ]:
# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
# Model Building


In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)

In [ ]:
# Prediction

In [ ]:
y_pred = model.predict(x_test)
y_pred

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [ ]:
ac = accuracy_score(y_test,y_pred)
cr = classification_report(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)

In [ ]:
ac

In [ ]:
cr

In [ ]:
cm

In [ ]:
plt.scatter(df1['EstimatedSalary'],df1['Purchased'])

In [ ]:
def logistic(x):
    return np.exp(x) /(1+np.exp(x))

x = np.linspace(-6,6,50,dtype=float)
y = logistic(x)
plt.plot(x,y)
plt.show()


# 1. Imports

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [17]:
data = load_breast_cancer()
data


{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [18]:
x = data.data
y = data.target

In [19]:
x.shape, y.shape

((569, 30), (569,))

# 3. Splitting

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=42, stratify=y)

In [21]:
x_train, x_test

(array([[1.162e+01, 1.818e+01, 7.638e+01, ..., 1.416e-01, 2.660e-01,
         9.270e-02],
        [1.120e+01, 2.937e+01, 7.067e+01, ..., 0.000e+00, 1.566e-01,
         5.905e-02],
        [1.057e+01, 1.832e+01, 6.682e+01, ..., 2.222e-02, 2.699e-01,
         6.736e-02],
        ...,
        [1.365e+01, 1.316e+01, 8.788e+01, ..., 8.056e-02, 2.380e-01,
         8.718e-02],
        [1.705e+01, 1.908e+01, 1.134e+02, ..., 2.543e-01, 3.109e-01,
         9.061e-02],
        [9.904e+00, 1.806e+01, 6.460e+01, ..., 9.910e-02, 2.614e-01,
         1.162e-01]]),
 array([[1.373e+01, 2.261e+01, 9.360e+01, ..., 2.208e-01, 3.596e-01,
         1.431e-01],
        [1.300e+01, 2.078e+01, 8.351e+01, ..., 6.296e-02, 3.196e-01,
         6.435e-02],
        [1.189e+01, 1.736e+01, 7.620e+01, ..., 8.946e-02, 2.220e-01,
         6.033e-02],
        ...,
        [1.650e+01, 1.829e+01, 1.066e+02, ..., 9.123e-02, 2.394e-01,
         6.469e-02],
        [1.343e+01, 1.963e+01, 8.584e+01, ..., 1.160e-01, 2.884e-01,
   

# 4. Feature Scaling

In [22]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# 5. Logistic Regression


In [24]:
model = LogisticRegression(max_iter=500, random_state=42)


# 6. Cross Validation

In [25]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [29]:
cv_score = cross_val_score(model, x_train, y_train, cv=cv, scoring = 'accuracy')
cv_score

array([1.        , 0.975     , 0.9875    , 1.        , 0.94936709])

In [ ]:
from sklearn.tree import plot_tree
plot_tree(model, filled=True, class_names=data.target_names, feature_names=data.feature_names)