# 2. Basic Syntax

In [2]:
a = int(input("Enter the 1st No."))
b = int(input("Enter the 2nd No."))
print(a+b)

30


In [12]:
# Print a multiline string using triple quotes
message = """This is line 1
This is line 2
This is line 3"""

print(message)

This is line 1
This is line 2
This is line 3


In [11]:
ip = input("Enter: ")
print(ip.upper())

SADASDSDASDA


In [22]:
lst = []
for _ in range(2):
    lst.append(int(input()))
print(lst)

[10, 12]


In [32]:
a = 10
b = 10.01
c = '10'
d = False
var = (a,b,c,d)
for i in range(len(var)):
    print(type(var[i]))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [34]:
a = b = c = 10
x,y,z = 1,2,3
var = (a,b,c,x,y,z)
for i in range(len(var)):
    print(var[i])

10
10
10
1
2
3


In [42]:
a = 50
b = 40
a,b = b,a
print(a,b)
a = a + b
b = a - b
a = a - b
print(a,b)

40 50
50 40


In [53]:
a = 10
b = 20
print(a*b)
c = 10.20
d = 20.30
print(c*d)
e = 3 + 4j
f = 4 + 2j
print(e/f)

200
207.06
(1+0.5j)


In [62]:
import math
degree = (30,45,60)
for i in range(len(degree)):
    print(math.sin(math.radians(degree[i])))
    print(math.sinh(math.radians(degree[i])))
    print(math.tan(math.radians(degree[i])))


0.49999999999999994
0.5478534738880397
0.5773502691896256
0.7071067811865475
0.8686709614860095
0.9999999999999999
0.8660254037844386
1.2493670505239751
1.7320508075688767


In [ ]:
import math
area = math.pi*
area

153.93804002589985

In [ ]:
st = input()
rev = st[::-1]
print(rev)
print(''.join(reversed(st)))
print(' '.join(st.split()[::-1]))

nahk si eman ym olleh
nahk si eman ym olleh
khan is name my hello


In [86]:
st = "I like Python"
if 'Python' in st:
    st = st.replace('Python','Java')
print(st)

for word in st.split():
    if word == 'Java':
        st = st.replace('Java','Python')
        break
print(st)

I like Java
I like Python


In [90]:
print("Hello\nHello\tHello")

Hello
Hello	Hello


In [92]:
'Hello' + 'hello'

'Hellohello'

In [99]:
name = 'Sheila'
print(f'My name is {name}')
print('My name is',name)
print('My name is %s'%(name))

My name is Sheila
My name is Sheila
My name is Sheila


In [ ]:
from collections import Counter
vow = ['a','e','i','o','u']
st = input().lower()
cnt = 0
# for i in range(len(st)):
#     for j in range(len(vow)):
#         if st[i] == vow[j]:
#             cnt = cnt+1

# freq = Counter(ch for ch in st if ch in vow)

for ch in st:
    if ch in vow:
        cnt = cnt+1
print(cnt)

2
2


In [126]:
import numpy as np
arr = np.random.randint(0,10,10)
ar = []
print(arr)
for a in arr:
    if a%2 == 0:
        ar.append(int(a))
print(ar)

[8 6 9 9 1 6 5 4 3 8]
[8, 6, 6, 4, 8]


In [128]:
op = int(input("Enter option (1-4): "))

match op:
    case 1:
        print("Option 1: Add")
        arr.append(int(input("Enter value: ")))
    case 2:
        print("Option 2: Remove")
        arr.pop() if arr else print("Empty!")
    case 3:
        print("Option 3: Display")
        print(arr)
    case 4:
        print("Exit")
    case _:
        print("Invalid option")

Invalid option


In [141]:
import numpy as np
arr = np.random.randint(0,10,10)
print(arr)
print(arr[::-1])
print(arr[:-3])
print(arr[:-3:-1])
print(arr[-3:])

[4 4 1 9 6 1 8 0 3 4]
[4 3 0 8 1 6 9 1 4 4]
[4 4 1 9 6 1 8]
[4 3]
[0 3 4]


In [198]:
import random as r
arr = []
arr1 = []
for _ in range(10):
    arr.append(r.randint(0,10))
    arr1.append(r.randint(0,10))
print(arr)
print(arr1)
arr.extend(arr1)
arr.insert(0,r.randint(0,10))
arr.remove(0)
arr.pop()
arr.sort()
arr.reverse()
print(arr)
k = 11
if k in arr:
    print("YES")
else:
    print("NO")

[7, 7, 7, 4, 5, 2, 8, 9, 4, 1]
[9, 0, 9, 4, 7, 4, 2, 4, 3, 1]
[9, 9, 9, 9, 8, 7, 7, 7, 7, 5, 4, 4, 4, 4, 4, 3, 2, 2, 1]
NO


In [183]:
tup = (10,20,30,40)
tup1 = (50,60,70,80)
print(tup[0])
print(tup[::-1])

arr = []
arr = list(tup)
arr.append(10)

tup.index(30)

10
(40, 30, 20, 10)


2

In [192]:
d = dict(name=["A","B"],roll=[1,2])
e = {"name":["C","D"],"roll":[3,4]}
print(d,e)

{'name': ['A', 'B'], 'roll': [1, 2]} {'name': ['C', 'D'], 'roll': [3, 4]}
