In [1]:
import numpy as np

## DataTypes and Attributes

### ndarray

In [6]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [22]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
type(a2)

numpy.ndarray

In [29]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [30]:
type(a3)

numpy.ndarray

In [23]:
a1.shape


(2, 3)

In [24]:
a2.shape

(2, 3)

In [25]:
a3.shape

(3, 2, 3)

In [28]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [32]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [33]:
a1.size,a2.size,a3.size

(3, 6, 18)

## 1. DataFrame from Numpy Array

In [35]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. Creating Arrays

In [36]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [37]:
sample_array.dtype

dtype('int64')

In [41]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
ones.dtype

dtype('float64')

In [44]:
zeroes = np.zeros((3,4))
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [48]:
random_array = np.random.randint(0,10,(3,5))
random_array

array([[2, 7, 6, 4, 1],
       [4, 4, 4, 4, 2],
       [4, 2, 4, 9, 4]])

In [51]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.28207365, 0.39423908, 0.22833287],
       [0.34103205, 0.18284539, 0.61726744],
       [0.0932692 , 0.52197379, 0.46624409],
       [0.22058566, 0.66831635, 0.58483907],
       [0.57469369, 0.98505332, 0.81635212]])

In [53]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.21828904, 0.54637292, 0.77790028],
       [0.03564233, 0.30303211, 0.11060931],
       [0.60893422, 0.66945316, 0.71566438],
       [0.28096845, 0.35753435, 0.44925188],
       [0.14075756, 0.6038631 , 0.66839004]])

## Pseudo-random numbers

In [64]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [74]:
np.random.seed(seed=0)
random_array_5 = np.random.randint(10, size=(2,3))
random_array_5


array([[5, 0, 3],
       [3, 7, 9]])

## 3. Viewing Arrays and Matrices

In [75]:
np.unique(random_array_5)

array([0, 3, 5, 7, 9])

In [82]:
a1.shape
# a1[0]

(3,)

In [83]:
a2.shape
# a2[0][0]

(2, 3)

In [84]:
a3.shape
# a3[0][0][0]

(3, 2, 3)

In [85]:
a3[:2, :2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [86]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [87]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[3, 5, 2, 4, 7],
         [6, 8, 8, 1, 6],
         [7, 7, 8, 1, 5],
         [9, 8, 9, 4, 3]],

        [[0, 3, 5, 0, 2],
         [3, 8, 1, 3, 3],
         [3, 7, 0, 1, 9],
         [9, 0, 4, 7, 3]],

        [[2, 7, 2, 0, 0],
         [4, 5, 5, 6, 8],
         [4, 1, 4, 9, 8],
         [1, 1, 7, 9, 9]]],


       [[[3, 6, 7, 2, 0],
         [3, 5, 9, 4, 4],
         [6, 4, 4, 3, 4],
         [4, 8, 4, 3, 7]],

        [[5, 5, 0, 1, 5],
         [9, 3, 0, 5, 0],
         [1, 2, 4, 2, 0],
         [3, 2, 0, 7, 5]],

        [[9, 0, 2, 7, 2],
         [9, 2, 3, 3, 2],
         [3, 4, 1, 2, 9],
         [1, 4, 6, 8, 2]]]])

In [88]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [96]:
#### Get the first 4 number of the inner most arrays
np.random.seed(0)
a4[:,:,:,:1]


array([[[[3],
         [6],
         [7],
         [9]],

        [[0],
         [3],
         [3],
         [9]],

        [[2],
         [4],
         [4],
         [1]]],


       [[[3],
         [3],
         [6],
         [4]],

        [[5],
         [9],
         [1],
         [3]],

        [[9],
         [9],
         [3],
         [1]]]])

## Manipulating and Comparing Arrays

### Arithmetic

#### 1-D

In [99]:
a1

array([1, 2, 3])

In [102]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [103]:
a1 + ones


array([2., 3., 4.])

In [104]:
a1 - ones


array([0., 1., 2.])

In [105]:
a1 * ones


array([1., 2., 3.])

In [106]:
a1 / ones

array([1., 2., 3.])

#### N-D

In [109]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [114]:
a2 * a3
# a2.shape, a3.shape

array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[  7,  16,  27],
        [ 40,  55,  72]],

       [[ 13,  28,  45],
        [ 64,  85, 108]]])

In [115]:
a4 = np.random.randint(10,size=(2,3,3))

In [116]:
a2 * a4

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 